#!/usr/bin/env python3
"""
RF vs PCA Loadings Comparison
=============================
Creates a two-column TXT file to compare Random Forest feature importances
with PCA loadings compressed as:
  total_contribution(feature) = sum_{i=1..8} (PCi_loading^2)

Inputs (expected, generated by existing pipeline):
- analysis_results/random_forest/feature_importance.csv
    columns: feature, importance
- analysis_results/pca/pca_loadings.csv
    index: feature names in first column
    columns: PC1, PC2, ..., PCk (PC1..PC8 used)

Output:
- analysis_results/RFvsPCAloadings/comparison.txt
    columns: rf_importance \t pca_total_contribution
    rows sorted by descending rf_importance; only features present in both files
"""

import os
import sys
import pandas as pd
from pathlib import Path


def main():
    script_dir = Path(__file__).parent
    rf_csv = script_dir / 'analysis_results' / 'random_forest' / 'feature_importance.csv'
    pca_csv = script_dir / 'analysis_results' / 'pca' / 'pca_loadings.csv'
    out_dir = script_dir / 'analysis_results' / 'RFvsPCAloadings'
    out_path = out_dir / 'comparison.txt'

    if not rf_csv.is_file():
        print(f"❌ Missing RF importances file: {rf_csv}")
        sys.exit(1)
    if not pca_csv.is_file():
        print(f"❌ Missing PCA loadings file: {pca_csv}")
        sys.exit(1)

    # Load RF importances
    rf_df = pd.read_csv(rf_csv)
    # Normalize column names
    rf_df.columns = [c.strip().lower() for c in rf_df.columns]
    if not {'feature', 'importance'}.issubset(rf_df.columns):
        print("❌ feature_importance.csv must contain columns: feature, importance")
        sys.exit(1)

    # Load PCA loadings with feature names as index
    # The CSV uses first unnamed column as feature names
    pca_df = pd.read_csv(pca_csv, index_col=0)
    # Normalize columns to lowercase for PC names
    pca_df.columns = [str(c).strip().lower() for c in pca_df.columns]

    # Determine PC columns (PC1..PC8 if present)
    pcs = [f'pc{i}' for i in range(1, 9)]
    pcs_available = [c for c in pcs if c in pca_df.columns]
    if len(pcs_available) == 0:
        print("❌ No PC1..PC8 columns found in pca_loadings.csv")
        sys.exit(1)

    # Compute total contribution = sum of squares across selected PCs
    pca_contrib = (pca_df[pcs_available] ** 2).sum(axis=1)
    pca_contrib.name = 'pca_total_contribution'
    pca_contrib_df = pca_contrib.reset_index()
    pca_contrib_df.columns = ['feature', 'pca_total_contribution']
    # Normalize feature names to exact strings used in RF CSV
    pca_contrib_df['feature'] = pca_contrib_df['feature'].astype(str)
    rf_df['feature'] = rf_df['feature'].astype(str)

    # Create independent rankings:
    # - RF: feature sorted by RF importance desc
    # - PCA: feature sorted by PCA total contribution desc
    rf_sorted = rf_df.sort_values('importance', ascending=False).reset_index(drop=True)
    pca_sorted = pca_contrib_df.sort_values('pca_total_contribution', ascending=False).reset_index(drop=True)

    # Prepare four-column TXT:
    # col1: feature (RF rank order)
    # col2: rf_importance
    # col3: feature (PCA rank order)
    # col4: pca_total_contribution
    out_dir.mkdir(parents=True, exist_ok=True)
    # Pre-compute column widths for clean left-aligned formatting
    rf_feat_col = ['feature_rf'] + rf_sorted['feature'].astype(str).tolist()
    rf_imp_col = ['rf_importance'] + [f"{v:.10f}" for v in rf_sorted['importance'].tolist()]
    pca_feat_col = ['feature_pca'] + pca_sorted['feature'].astype(str).tolist()
    pca_contrib_col = ['pca_total_contribution'] + [f"{v:.10f}" for v in pca_sorted['pca_total_contribution'].tolist()]
    w1 = max(len(s) for s in rf_feat_col) + 2
    w2 = max(len(s) for s in rf_imp_col) + 2
    w3 = max(len(s) for s in pca_feat_col) + 2
    w4 = max(len(s) for s in pca_contrib_col) + 2

    with open(out_path, 'w', encoding='utf-8') as f:
        header = f"{'feature_rf':<{w1}}{'rf_importance':<{w2}}{'feature_pca':<{w3}}{'pca_total_contribution':<{w4}}"
        f.write(header.rstrip() + "\n")
        n = max(len(rf_sorted), len(pca_sorted))
        for i in range(n):
            rf_feat = (rf_sorted.iloc[i]['feature'] if i < len(rf_sorted) else "")
            rf_imp = (f"{rf_sorted.iloc[i]['importance']:.10f}" if i < len(rf_sorted) else "")
            pca_feat = (pca_sorted.iloc[i]['feature'] if i < len(pca_sorted) else "")
            pca_contrib_val = (f"{pca_sorted.iloc[i]['pca_total_contribution']:.10f}" if i < len(pca_sorted) else "")
            line = f"{str(rf_feat):<{w1}}{str(rf_imp):<{w2}}{str(pca_feat):<{w3}}{str(pca_contrib_val):<{w4}}"
            f.write(line.rstrip() + "\n")

    print(f"✓ Saved comparison: {out_path}")


if __name__ == '__main__':
    main()

